[package]
name = "rem-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rem-borrower = { git = "https://github.com/RuleBrittonica/rem-borrower.git", branch = "master" }
rem-controller = { git = "https://github.com/RuleBrittonica/rem-controller.git", branch = "master" }
rem-repairer = { git ="https://github.com/RuleBrittonica/rem-repairer.git", branch = "master" }
rem-utils = { git = "https://github.com/RuleBrittonica/rem-utils.git", branch = "master" }
clap = "4.5.16"
log = "0.4.22"
flexi_logger = "0.28.5"
lsp-server = "0.7.6"
lsp-types = "0.97.0"
serde_json = "1.0.127"
serde = "1.0.209"
tokio = "1.39.3"
tower-lsp = "0.20.0"
futures = "0.3.30"
colored = "2.1.0"
