(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module RemCli.

(** [rem_cli::ref_incr]:
    Source: '/home/matt/rem-matt/rem-cli/test_crates/sample_project/src/main.rs', lines 5:0-7:1 *)
Definition ref_incr (x : i32) : result i32 :=
  i32_add x 1%i32.

(** [rem_cli::test_incr]:
    Source: '/home/matt/rem-matt/rem-cli/test_crates/sample_project/src/main.rs', lines 9:0-13:1 *)
Definition test_incr : result unit :=
  y <- ref_incr 0%i32; massert (y s= 1%i32)
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/test_crates/sample_project/src/main.rs', lines 1:0-3:1 *)
Definition main : result unit :=
  test_incr.

End RemCli.
