(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ArgumentAndLocals.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/argument_and_locals.rs', lines 1:0-5:1 *)
Definition foo : result u32 :=
  u32_add 2%u32 1%u32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/argument_and_locals.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End ArgumentAndLocals.rs.
