(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ArgumentAndLocalsRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/argument_and_locals_ref.rs', lines 6:0-9:1 *)
Definition fun_name (n : u32) : result u32 :=
  u32_add n 1%u32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/argument_and_locals_ref.rs', lines 1:0-4:1 *)
Definition foo : result u32 :=
  fun_name 2%u32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/argument_and_locals_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End ArgumentAndLocalsRef.rs.
