(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BreakLoopNestedLabeled.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_nested_labeled.rs', lines 1:0-7:1 *)
Definition foo : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_nested_labeled.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End BreakLoopNestedLabeled.rs.
