(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BreakLoopNested.rs.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_nested.rs', lines 2:4-9:5 *)
Fixpoint foo_loop : result unit :=
  m <- i32_add 1%i32 1%i32; if m s= 42%i32 then Ok tt else foo_loop
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_nested.rs', lines 1:0-10:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_nested.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End BreakLoopNested.rs.
