(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BreakWithValueAndLabelRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_with_value_and_label_ref.rs', lines 11:0-18:1 *)
Definition fun_name : result (option i32) :=
  if 1%i32 s= 42%i32
  then Ok (Some 4%i32)
  else (_ <- i32_add 1%i32 1%i32; Ok None)
.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_with_value_and_label_ref.rs', lines 2:4-8:5 *)
Fixpoint foo_loop : result i32 :=
  o <- fun_name; match o with | None => foo_loop | Some value => Ok value end
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_with_value_and_label_ref.rs', lines 1:0-9:1 *)
Definition foo : result i32 :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_with_value_and_label_ref.rs', lines 20:0-22:1 *)
Definition main : result unit :=
  Ok tt.

End BreakWithValueAndLabelRef.rs.
