(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BreakLoopRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_ref.rs', lines 12:0-17:1 *)
Definition fun_name (n : i32) : result (option i32) :=
  _ <- i32_add n 1%i32; Ok None
.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_ref.rs', lines 2:4-9:5 *)
Fixpoint foo_loop : result unit :=
  o <- fun_name 1%i32;
  match o with
  | None => Ok tt
  | Some value => _ <- i32_add 1%i32 value; foo_loop
  end
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_ref.rs', lines 1:0-10:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_ref.rs', lines 19:0-21:1 *)
Definition main : result unit :=
  Ok tt.

End BreakLoopRef.rs.
