(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module BreakLoopWithIf.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_with_if.rs', lines 1:0-9:1 *)
Definition foo : result unit :=
  _ <- i32_add 1%i32 1%i32; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/break_loop_with_if.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End BreakLoopWithIf.rs.
