(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module CommentsInBlockExprRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/comments_in_block_expr_ref.rs', lines 5:0-11:1 *)
Definition fun_name : result i32 :=
  a <- i32_add 2%i32 3%i32; i32_add a 5%i32.

(** [rem_cli::f]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/comments_in_block_expr_ref.rs', lines 1:0-3:1 *)
Definition f : result unit :=
  _ <- fun_name; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/comments_in_block_expr_ref.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End CommentsInBlockExprRef.rs.
