(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module CommentsInBlockExpr.rs.

(** [rem_cli::f]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/comments_in_block_expr.rs', lines 1:0-9:1 *)
Definition f : result unit :=
  a <- i32_add 2%i32 3%i32; _ <- i32_add a 5%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/comments_in_block_expr.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End CommentsInBlockExpr.rs.
