(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ContinueLoopNestedLabeledRef.rs.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 85:0-85:31
    Name pattern: core::ops::control_flow::ControlFlow *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/continue_loop_nested_labeled_ref.rs', lines 13:0-16:1 *)
Definition fun_name : result (core_ops_control_flow_ControlFlow_t unit unit) :=
  Ok (Core_ops_control_flow_ControlFlow_Break tt)
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/continue_loop_nested_labeled_ref.rs', lines 3:0-11:1 *)
Axiom foo : result unit.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/continue_loop_nested_labeled_ref.rs', lines 18:0-20:1 *)
Definition main : result unit :=
  Ok tt.

End ContinueLoopNestedLabeledRef.rs.
