(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module CopyUsedAfterRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_used_after_ref.rs', lines 7:0-9:1 *)
Definition fun_name (n : i32) : result unit :=
  Ok tt.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_used_after_ref.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  fun_name 0%i32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_used_after_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End CopyUsedAfterRef.rs.
