(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module CopyCustomUsedAfter.rs.

(** [rem_cli::Counter]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 2:0-2:20 *)
Definition Counter_t : Type := i32.

(** [rem_cli::{core::clone::Clone for rem_cli::Counter}::clone]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 1:9-1:14 *)
Definition clonerem_cliCounter_clone (self : Counter_t) : result Counter_t :=
  Ok self
.

(** Trait implementation: [rem_cli::{core::clone::Clone for rem_cli::Counter}]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 1:9-1:14 *)
Definition core_clone_Clonerem_cliCounter : core_clone_Clone Counter_t := {|
  core_clone_Clone_clone := clonerem_cliCounter_clone;
|}.

(** Trait implementation: [rem_cli::{core::marker::Copy for rem_cli::Counter}#1]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 1:16-1:20 *)
Definition core_marker_Copyrem_cliCounter : core_marker_Copy Counter_t := {|
  cloneInst := core_clone_Clonerem_cliCounter;
|}.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 3:0-7:1 *)
Definition foo : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/copy_custom_used_after.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End CopyCustomUsedAfter.rs.
