(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module DoesNotImportControlFlowRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/does_not_import_control_flow_ref.rs', lines 5:0-7:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/does_not_import_control_flow_ref.rs', lines 1:0-3:1 *)
Definition func : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/does_not_import_control_flow_ref.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End DoesNotImportControlFlowRef.rs.
