(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionCopiesCommentIndented.rs.

(** [rem_cli::func]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented.rs', lines 4:4-6:5 *)
Fixpoint func_loop : result unit :=
  func_loop.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented.rs', lines 1:0-7:1 *)
Definition func : result unit :=
  func_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionCopiesCommentIndented.rs.
