(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractDoesNotTearCommentsApartRef.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_comments_apart_ref.rs', lines 1:0-3:1 *)
Fixpoint foo : result unit :=
  fun_name

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_comments_apart_ref.rs', lines 5:0-10:1 *)
with fun_name : result unit :=
  _ <- foo; foo.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_comments_apart_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractDoesNotTearCommentsApartRef.rs.
