(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionFromTraitWithExistingNonEmptyImplBlockRef.rs.

(** [rem_cli::Struct]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 1:0-1:19 *)
Definition Struct_t : Type := i32.

(** Trait declaration: [rem_cli::Trait]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 2:0-4:1 *)
Record Trait_t (Self : Type) := mkTrait_t { Trait_t_bar : Self -> result i32;
}.

Arguments mkTrait_t { _ }.
Arguments Trait_t_bar { _ } _.

(** [rem_cli::{rem_cli::Struct}::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 7:4-7:15 *)
Definition struct_foo : result unit :=
  Ok tt.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 17:0-19:1 *)
Definition fun_name : result i32 :=
  i32_mul 3%i32 3%i32.

(** [rem_cli::{rem_cli::Trait for rem_cli::Struct}#1::bar]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 11:4-14:5 *)
Definition traitrem_cliStruct_bar (self : Struct_t) : result i32 :=
  three_squared <- fun_name; i32_add self three_squared
.

(** Trait implementation: [rem_cli::{rem_cli::Trait for rem_cli::Struct}#1]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 10:0-15:1 *)
Definition Traitrem_cliStruct : Trait_t Struct_t := {|
  Trait_t_bar := traitrem_cliStruct_bar;
|}.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_from_trait_with_existing_non_empty_impl_block_ref.rs', lines 21:0-23:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionFromTraitWithExistingNonEmptyImplBlockRef.rs.
