(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractPartialBlockRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block_ref.rs', lines 9:0-13:1 *)
Definition fun_name (m : i32) (n : i32) : result (i32 * i32) :=
  v <- i32_mul m n; Ok (v, 3%i32)
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block_ref.rs', lines 1:0-7:1 *)
Definition foo : result unit :=
  p <- fun_name 2%i32 1%i32;
  let (v, w) := p in
  _ <- i32_add v 1%i32;
  _ <- i32_add w 1%i32;
  Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block_ref.rs', lines 15:0-17:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractPartialBlockRef.rs.
