(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractPartialBlockSingleLine.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block_single_line.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  v <- i32_mul 1%i32 1%i32; _ <- i32_add v 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block_single_line.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractPartialBlockSingleLine.rs.
