(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractPartialBlock.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block.rs', lines 1:0-8:1 *)
Definition foo : result unit :=
  v <- i32_mul 2%i32 1%i32;
  _ <- i32_add v 1%i32;
  _ <- i32_add 3%i32 1%i32;
  Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_partial_block.rs', lines 10:0-12:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractPartialBlock.rs.
