(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionCopiesCommentIndentedRef.rs.

(** [rem_cli::fun_name]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented_ref.rs', lines 8:4-10:5 *)
Fixpoint fun_name_loop : result unit :=
  fun_name_loop.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented_ref.rs', lines 6:0-11:1 *)
Definition fun_name : result unit :=
  fun_name_loop.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented_ref.rs', lines 1:0-4:1 *)
Definition func : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_indented_ref.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionCopiesCommentIndentedRef.rs.
