(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractMethodFromTraitImplRef.rs.

(** [rem_cli::Struct]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 1:0-1:19 *)
Definition Struct_t : Type := i32.

(** Trait declaration: [rem_cli::Trait]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 2:0-4:1 *)
Record Trait_t (Self : Type) := mkTrait_t { Trait_t_bar : Self -> result i32;
}.

Arguments mkTrait_t { _ }.
Arguments Trait_t_bar { _ } _.

(** [rem_cli::{rem_cli::Struct}#1::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 13:4-15:5 *)
Definition struct_fun_name (self : Struct_t) : result i32 :=
  i32_add self 2%i32
.

(** [rem_cli::{rem_cli::Trait for rem_cli::Struct}::bar]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 7:4-9:5 *)
Definition traitrem_cliStruct_bar (self : Struct_t) : result i32 :=
  struct_fun_name self
.

(** Trait implementation: [rem_cli::{rem_cli::Trait for rem_cli::Struct}]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 6:0-10:1 *)
Definition Traitrem_cliStruct : Trait_t Struct_t := {|
  Trait_t_bar := traitrem_cliStruct_bar;
|}.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_impl_ref.rs', lines 18:0-20:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractMethodFromTraitImplRef.rs.
