(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractDoesNotTearBodyApartRef.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_body_apart_ref.rs', lines 1:0-3:1 *)
Fixpoint foo : result unit :=
  fun_name

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_body_apart_ref.rs', lines 5:0-7:1 *)
with fun_name : result unit :=
  foo.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_body_apart_ref.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractDoesNotTearBodyApartRef.rs.
