(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractReturnStmt.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_return_stmt.rs', lines 1:0-3:1 *)
Definition foo : result u32 :=
  u32_add 2%u32 2%u32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_return_stmt.rs', lines 5:0-7:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractReturnStmt.rs.
