(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractMutRefParamHasNoMutBindingInLoopRef.rs.

(** [rem_cli::Foo]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 1:0-1:11 *)
Definition Foo_t : Type := unit.

(** [rem_cli::{rem_cli::Foo}::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 3:4-3:24 *)
Definition foo_foo (self : Foo_t) : result Foo_t :=
  Ok self.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 14:0-16:1 *)
Definition fun_name (y : Foo_t) : result Foo_t :=
  foo_foo y.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 7:4-10:5 *)
Definition foo_loop : result unit :=
  Ok tt.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 5:0-12:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_mut_ref_param_has_no_mut_binding_in_loop_ref.rs', lines 18:0-20:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractMutRefParamHasNoMutBindingInLoopRef.rs.
