(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionLongFormCommentRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_long_form_comment_ref.rs', lines 6:0-9:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_long_form_comment_ref.rs', lines 1:0-4:1 *)
Definition func : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_long_form_comment_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionLongFormCommentRef.rs.
