(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractMethodFromTraitWithMultipleExistingImplBlocks.rs.

(** [rem_cli::Struct]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 1:0-1:19 *)
Definition Struct_t : Type := i32.

(** [rem_cli::StructBefore]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 2:0-2:25 *)
Definition StructBefore_t : Type := i32.

(** [rem_cli::StructAfter]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 3:0-3:24 *)
Definition StructAfter_t : Type := i32.

(** Trait declaration: [rem_cli::Trait]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 4:0-6:1 *)
Record Trait_t (Self : Type) := mkTrait_t { Trait_t_bar : Self -> result i32;
}.

Arguments mkTrait_t { _ }.
Arguments Trait_t_bar { _ } _.

(** [rem_cli::{rem_cli::StructBefore}::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 9:4-9:14 *)
Definition structBefore_foo : result unit :=
  Ok tt.

(** [rem_cli::{rem_cli::Struct}#1::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 13:4-13:14 *)
Definition struct_foo : result unit :=
  Ok tt.

(** [rem_cli::{rem_cli::StructAfter}#2::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 17:4-17:14 *)
Definition structAfter_foo : result unit :=
  Ok tt.

(** [rem_cli::{rem_cli::Trait for rem_cli::Struct}#3::bar]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 21:4-23:5 *)
Definition traitrem_cliStruct_bar (self : Struct_t) : result i32 :=
  i32_add self 2%i32
.

(** Trait implementation: [rem_cli::{rem_cli::Trait for rem_cli::Struct}#3]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 20:0-24:1 *)
Definition Traitrem_cliStruct : Trait_t Struct_t := {|
  Trait_t_bar := traitrem_cliStruct_bar;
|}.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_method_from_trait_with_multiple_existing_impl_blocks.rs', lines 26:0-28:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractMethodFromTraitWithMultipleExistingImplBlocks.rs.
