(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractDoesNotTearCommentsApart.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_comments_apart.rs', lines 1:0-6:1 *)
Fixpoint foo : result unit :=
  _ <- foo; foo.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_does_not_tear_comments_apart.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractDoesNotTearCommentsApart.rs.
