(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionDoesPreserveWhitespace.rs.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_does_preserve_whitespace.rs', lines 1:0-6:1 *)
Definition func : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_does_preserve_whitespace.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionDoesPreserveWhitespace.rs.
