(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionLongFormComment.rs.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_long_form_comment.rs', lines 1:0-5:1 *)
Definition func : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_long_form_comment.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionLongFormComment.rs.
