(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ExtractFunctionCopiesCommentInBetweenRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_in_between_ref.rs', lines 6:0-10:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_in_between_ref.rs', lines 1:0-4:1 *)
Definition func : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/extract_function_copies_comment_in_between_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End ExtractFunctionCopiesCommentInBetweenRef.rs.
