(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module IndentedStmtsInsideMod.rs.

(** [rem_cli::bar::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod.rs', lines 4:12-7:13 *)
Fixpoint bar_foo_loop : result unit :=
  bar_foo_loop.

(** [rem_cli::bar::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod.rs', lines 2:4-9:5 *)
Definition bar_foo : result unit :=
  bar_foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End IndentedStmtsInsideMod.rs.
