(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module IndentedStmtsRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_ref.rs', lines 9:0-12:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_ref.rs', lines 3:8-5:9 *)
Fixpoint foo_loop : result unit :=
  _ <- fun_name; foo_loop.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_ref.rs', lines 1:0-7:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_ref.rs', lines 14:0-16:1 *)
Definition main : result unit :=
  Ok tt.

End IndentedStmtsRef.rs.
