(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module IndentedStmtsInsideModRef.rs.

(** [rem_cli::bar::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod_ref.rs', lines 10:4-13:5 *)
Definition bar_fun_name : result unit :=
  Ok tt.

(** [rem_cli::bar::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod_ref.rs', lines 4:12-6:13 *)
Fixpoint bar_foo_loop : result unit :=
  _ <- bar_fun_name; bar_foo_loop.

(** [rem_cli::bar::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod_ref.rs', lines 2:4-8:5 *)
Definition bar_foo : result unit :=
  bar_foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/indented_stmts_inside_mod_ref.rs', lines 16:0-18:1 *)
Definition main : result unit :=
  Ok tt.

End IndentedStmtsInsideModRef.rs.
