(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ItShouldNotGenerateDuplicateFunctionNames.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/it_should_not_generate_duplicate_function_names.rs', lines 1:0-3:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/it_should_not_generate_duplicate_function_names.rs', lines 5:0-7:1 *)
Definition main : result unit :=
  Ok tt.

End ItShouldNotGenerateDuplicateFunctionNames.rs.
