(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MultiVariablesDefinedInsideAndUsedAfterMutablyNoRetRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/multi_variables_defined_inside_and_used_after_mutably_no_ret_ref.rs', lines 8:0-14:1 *)
Definition fun_name (n : i32) : result (i32 * i32 * i32) :=
  k <- i32_mul n n;
  m <- i32_add k 2%i32;
  o <- i32_add m 3%i32;
  o1 <- i32_add o 1%i32;
  Ok (k, m, o1)
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/multi_variables_defined_inside_and_used_after_mutably_no_ret_ref.rs', lines 1:0-6:1 *)
Definition foo : result unit :=
  t <- fun_name 1%i32; let '(k, _, o) := t in _ <- i32_add k o; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/multi_variables_defined_inside_and_used_after_mutably_no_ret_ref.rs', lines 16:0-18:1 *)
Definition main : result unit :=
  Ok tt.

End MultiVariablesDefinedInsideAndUsedAfterMutablyNoRetRef.rs.
