(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MultiVariablesDefinedInsideAndUsedAfterMutablyNoRet.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/multi_variables_defined_inside_and_used_after_mutably_no_ret.rs', lines 1:0-9:1 *)
Definition foo : result unit :=
  k <- i32_mul 1%i32 1%i32;
  m <- i32_add k 2%i32;
  o <- i32_add m 3%i32;
  o1 <- i32_add o 1%i32;
  _ <- i32_add k o1;
  Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/multi_variables_defined_inside_and_used_after_mutably_no_ret.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End MultiVariablesDefinedInsideAndUsedAfterMutablyNoRet.rs.
