(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutFieldFromOuterScope.rs.

(** [rem_cli::C]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope.rs', lines 1:0-1:19 *)
Record C_t := mkC_t { c_n : i32; }.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope.rs', lines 2:0-6:1 *)
Definition foo : result unit :=
  i <- i32_add 0%i32 1%i32; _ <- i32_add i 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End MutFieldFromOuterScope.rs.
