(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutFieldFromOuterScopeRef.rs.

(** [rem_cli::C]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope_ref.rs', lines 1:0-1:19 *)
Record C_t := mkC_t { c_n : i32; }.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope_ref.rs', lines 8:0-10:1 *)
Definition fun_name (c : C_t) : result C_t :=
  i <- i32_add c.(c_n) 1%i32; Ok {| c_n := i |}
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope_ref.rs', lines 2:0-6:1 *)
Definition foo : result unit :=
  c <- fun_name {| c_n := 0%i32 |}; _ <- i32_add c.(c_n) 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_field_from_outer_scope_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End MutFieldFromOuterScopeRef.rs.
