(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutMethodCallRef.rs.

(** Trait declaration: [rem_cli::I]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 1:0-3:1 *)
Record I_t (Self : Type) := mkI_t { I_t_inc : Self -> result Self; }.

Arguments mkI_t { _ }.
Arguments I_t_inc { _ } _.

(** [rem_cli::{rem_cli::I for i32}::inc]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 5:4-5:36 *)
Definition iI32_inc (self : i32) : result i32 :=
  i32_add self 1%i32.

(** Trait implementation: [rem_cli::{rem_cli::I for i32}]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 4:0-6:1 *)
Definition II32 : I_t i32 := {| I_t_inc := iI32_inc; |}.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 12:0-14:1 *)
Definition fun_name (n : i32) : result unit :=
  _ <- iI32_inc n; Ok tt.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 7:0-10:1 *)
Definition foo : result unit :=
  fun_name 1%i32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_method_call_ref.rs', lines 16:0-18:1 *)
Definition main : result unit :=
  Ok tt.

End MutMethodCallRef.rs.
