(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutNestedFieldFromOuterScope.rs.

(** [rem_cli::P]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_nested_field_from_outer_scope.rs', lines 1:0-1:18 *)
Record P_t := mkP_t { p_n : i32; }.

(** [rem_cli::C]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_nested_field_from_outer_scope.rs', lines 2:0-2:17 *)
Record C_t := mkC_t { c_p : P_t; }.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_nested_field_from_outer_scope.rs', lines 3:0-10:1 *)
Definition foo : result unit :=
  i <- i32_add 0%i32 0%i32; i1 <- i32_add i 0%i32; _ <- i32_add i1 0%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_nested_field_from_outer_scope.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End MutNestedFieldFromOuterScope.rs.
