(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutParamBecauseOfMutRef.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_param_because_of_mut_ref.rs', lines 1:0-6:1 *)
Definition foo : result unit :=
  _ <- i32_add 1%i32 1%i32; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_param_because_of_mut_ref.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End MutParamBecauseOfMutRef.rs.
