(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutVarFromOuterScopeRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_var_from_outer_scope_ref.rs', lines 7:0-9:1 *)
Definition fun_name (n : i32) : result i32 :=
  i32_add n 1%i32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_var_from_outer_scope_ref.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  n <- fun_name 1%i32; _ <- i32_add n 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_var_from_outer_scope_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End MutVarFromOuterScopeRef.rs.
