(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module MutVarFromOuterScope.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_var_from_outer_scope.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  n <- i32_add 1%i32 1%i32; _ <- i32_add n 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/mut_var_from_outer_scope.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End MutVarFromOuterScope.rs.
