(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromLoopWithReturn.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_with_return.rs', lines 1:0-6:1 *)
Definition foo : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_with_return.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromLoopWithReturn.rs.
