(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromStmtWithLastExprRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_with_last_expr_ref.rs', lines 6:0-9:1 *)
Definition fun_name : result i32 :=
  i32_add 1%i32 1%i32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_with_last_expr_ref.rs', lines 1:0-4:1 *)
Definition foo : result i32 :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_with_last_expr_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromStmtWithLastExprRef.rs.
