(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsIfLetElse.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_if_let_else.rs', lines 1:0-3:1 *)
Definition foo : result i32 :=
  Ok 2%i32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_if_let_else.rs', lines 5:0-7:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsIfLetElse.rs.
