(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromStmtWithLastExpr.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_with_last_expr.rs', lines 1:0-5:1 *)
Definition foo : result i32 :=
  i32_add 1%i32 1%i32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_with_last_expr.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromStmtWithLastExpr.rs.
