(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromLoopUnit.rs.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_unit.rs', lines 2:4-4:5 *)
Fixpoint foo_loop : result unit :=
  foo_loop.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_unit.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_unit.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromLoopUnit.rs.
