(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromStmtUnitRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_unit_ref.rs', lines 7:0-10:1 *)
Definition fun_name : result unit :=
  _ <- i32_add 1%i32 1%i32; Ok tt.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_unit_ref.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_stmt_unit_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromStmtUnitRef.rs.
