(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromBinaryExprIndented.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_binary_expr_indented.rs', lines 1:0-3:1 *)
Definition foo : result unit :=
  _ <- i32_add 1%i32 1%i32; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_binary_expr_indented.rs', lines 5:0-7:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromBinaryExprIndented.rs.
