(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsWhileRef.rs.

(** [rem_cli::fun_name]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_while_ref.rs', lines 6:4-6:18 *)
Fixpoint fun_name_loop : result unit :=
  fun_name_loop.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_while_ref.rs', lines 5:0-7:1 *)
Definition fun_name : result unit :=
  fun_name_loop.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_while_ref.rs', lines 1:0-3:1 *)
Definition foo : result unit :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_while_ref.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsWhileRef.rs.
