(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NoArgsFromLoopUnitRef.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_unit_ref.rs', lines 1:0-3:1 *)
Definition foo : result unit :=
  admit.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/no_args_from_loop_unit_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End NoArgsFromLoopUnitRef.rs.
