(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NontrivialPatternsDefineVariablesRef.rs.

(** [rem_cli::Counter]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables_ref.rs', lines 1:0-1:20 *)
Definition Counter_t : Type := i32.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables_ref.rs', lines 7:0-10:1 *)
Definition fun_name : result i32 :=
  Ok 0%i32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables_ref.rs', lines 2:0-5:1 *)
Definition foo : result unit :=
  _ <- fun_name; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End NontrivialPatternsDefineVariablesRef.rs.
