(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NonTailExprOfTailExprLoop.rs.

(** [rem_cli::f]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_expr_loop.rs', lines 1:0-10:5 *)
Fixpoint f_loop : result unit :=
  f_loop.

(** [rem_cli::f]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_expr_loop.rs', lines 1:0-11:1 *)
Definition f : result unit :=
  f_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_expr_loop.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End NonTailExprOfTailExprLoop.rs.
