(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NontrivialPatternsDefineVariables.rs.

(** [rem_cli::Counter]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables.rs', lines 1:0-1:20 *)
Definition Counter_t : Type := i32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables.rs', lines 2:0-5:1 *)
Definition foo : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/nontrivial_patterns_define_variables.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End NontrivialPatternsDefineVariables.rs.
