(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module NonTailExprOfTailIfBlockRef.rs.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 85:0-85:31
    Name pattern: core::ops::control_flow::ControlFlow *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 904:0-904:19
    Name pattern: core::convert::Infallible *)
Inductive core_convert_Infallible_t :=.

(** [core::option::{core::ops::try_trait::Try for core::option::Option<T>}#39::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2479:4-2479:64
    Name pattern: core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch *)
Axiom core_option_TryOption_branch :
  forall{T : Type},
        option T -> result (core_ops_control_flow_ControlFlow_t (option
          core_convert_Infallible_t) T)
.

(** [core::option::{core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}#40::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2492:4-2492:67
    Name pattern: core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual *)
Axiom core_option_FromResidualOptionOptioncoreconvertInfallible_from_residual :
  forall(T : Type), option core_convert_Infallible_t -> result (option T)
.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_if_block_ref.rs', lines 10:0-16:1 *)
Definition fun_name : result (option unit) :=
  cf <- core_option_TryOption_branch (Some tt);
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue _ => Ok (Some tt)
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_FromResidualOptionOptioncoreconvertInfallible_from_residual
      unit residual
  end
.

(** [rem_cli::f]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_if_block_ref.rs', lines 1:0-8:1 *)
Definition f : result (option unit) :=
  o <- fun_name;
  cf <- core_option_TryOption_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue _ => Ok (Some tt)
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_FromResidualOptionOptioncoreconvertInfallible_from_residual
      unit residual
  end
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/non_tail_expr_of_tail_if_block_ref.rs', lines 18:0-20:1 *)
Definition main : result unit :=
  Ok tt.

(** Trait declaration: [core::ops::try_trait::FromResidual]
    Source: '/rustc/library/core/src/ops/try_trait.rs', lines 307:0-307:51
    Name pattern: core::ops::try_trait::FromResidual *)
Record core_ops_try_trait_FromResidual_t (Self : Type) (R : Type)
  := mkcore_ops_try_trait_FromResidual_t {
  core_ops_try_trait_FromResidual_t_from_residual : R -> result Self;
}.

Arguments mkcore_ops_try_trait_FromResidual_t { _ } { _ }.
Arguments core_ops_try_trait_FromResidual_t_from_residual { _ } { _ } _.

(** Trait declaration: [core::ops::try_trait::Try]
    Source: '/rustc/library/core/src/ops/try_trait.rs', lines 131:0-131:27
    Name pattern: core::ops::try_trait::Try *)
Record core_ops_try_trait_Try_t (Self : Type) := mkcore_ops_try_trait_Try_t {
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Output : Type;
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Residual : Type;
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_FromResidualSelfcoreopstry_traitTryResidualInst
    : core_ops_try_trait_FromResidual_t Self
    core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Residual;
  core_ops_try_trait_Try_t_from_output :
    core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Output -> result Self;
  core_ops_try_trait_Try_t_branch : Self -> result
    (core_ops_control_flow_ControlFlow_t
    core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Residual
    core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Output);
}.

Arguments mkcore_ops_try_trait_Try_t { _ }.
Arguments core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Output { _ } _.
Arguments core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Residual { _ } _.
Arguments
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_FromResidualSelfcoreopstry_traitTryResidualInst
  { _ } _.
Arguments core_ops_try_trait_Try_t_from_output { _ } _.
Arguments core_ops_try_trait_Try_t_branch { _ } _.

(** Trait implementation: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}#40]
    Source: '/rustc/library/core/src/option.rs', lines 2490:0-2490:68
    Name pattern: core::ops::try_trait::FromResidual<core::option::Option<@Self>, core::option::Option<core::convert::Infallible>> *)
Definition core_ops_try_trait_FromResidualOptionOptioncoreconvertInfallible (T
  : Type) : core_ops_try_trait_FromResidual_t (option T) (option
  core_convert_Infallible_t) := {|
  core_ops_try_trait_FromResidual_t_from_residual :=
    core_option_FromResidualOptionOptioncoreconvertInfallible_from_residual T;
|}.

(** [core::option::{core::ops::try_trait::Try for core::option::Option<T>}#39::from_output]:
    Source: '/rustc/library/core/src/option.rs', lines 2474:4-2474:48
    Name pattern: core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::from_output *)
Axiom core_option_TryOption_from_output :
  forall{T : Type}, T -> result (option T)
.

(** Trait implementation: [core::option::{core::ops::try_trait::Try for core::option::Option<T>}#39]
    Source: '/rustc/library/core/src/option.rs', lines 2469:0-2469:30
    Name pattern: core::ops::try_trait::Try<core::option::Option<@Self>> *)
Definition core_ops_try_trait_TryOption (T : Type) : core_ops_try_trait_Try_t
  (option T) := {|
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Output := T;
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_Residual := option
    core_convert_Infallible_t;
  core_ops_try_trait_Try_tcore_ops_try_trait_Try_t_FromResidualSelfcoreopstry_traitTryResidualInst
    := core_ops_try_trait_FromResidualOptionOptioncoreconvertInfallible T;
  core_ops_try_trait_Try_t_from_output := core_option_TryOption_from_output;
  core_ops_try_trait_Try_t_branch := core_option_TryOption_branch;
|}.

End NonTailExprOfTailIfBlockRef.rs.
