(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacroWithNestedTt2.rs.

(** [rem_cli::S]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2.rs', lines 5:0-5:14 *)
Definition S_t : Type := i32.

(** [rem_cli::{rem_cli::S}::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2.rs', lines 7:4-11:5 *)
Definition s_foo (self : S_t) : result unit :=
  i <- i32_add 1%i32 self; k <- i32_mul 1%i32 i; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2.rs', lines 14:0-16:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacroWithNestedTt2.rs.
