(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacroRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_ref.rs', lines 11:0-14:1 *)
Definition fun_name (n : i32) : result i32 :=
  i32_mul n n.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_ref.rs', lines 5:0-9:1 *)
Definition foo : result unit :=
  k <- fun_name 1%i32; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_ref.rs', lines 16:0-18:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacroRef.rs.
