(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacroWithNestedTt2Ref.rs.

(** [rem_cli::S]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2_ref.rs', lines 5:0-5:14 *)
Definition S_t : Type := i32.

(** [rem_cli::{rem_cli::S}::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2_ref.rs', lines 13:4-16:5 *)
Definition s_fun_name (self : S_t) (n : i32) : result i32 :=
  i <- i32_add n self; i32_mul n i
.

(** [rem_cli::{rem_cli::S}::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2_ref.rs', lines 7:4-11:5 *)
Definition s_foo (self : S_t) : result unit :=
  k <- s_fun_name self 1%i32; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_2_ref.rs', lines 19:0-21:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacroWithNestedTt2Ref.rs.
