(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacro.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro.rs', lines 5:0-9:1 *)
Definition foo : result unit :=
  k <- i32_mul 1%i32 1%i32; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacro.rs.
