(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacroWithNestedTtRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_ref.rs', lines 12:0-15:1 *)
Definition fun_name (n : i32) (t : i32) : result i32 :=
  i <- i32_add n t; i32_mul n i
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_ref.rs', lines 5:0-10:1 *)
Definition foo : result unit :=
  k <- fun_name 1%i32 1%i32; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt_ref.rs', lines 17:0-19:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacroWithNestedTtRef.rs.
