(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ParamUsageInMacroWithNestedTt.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt.rs', lines 5:0-10:1 *)
Definition foo : result unit :=
  i <- i32_add 1%i32 1%i32; k <- i32_mul 1%i32 i; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/param_usage_in_macro_with_nested_tt.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End ParamUsageInMacroWithNestedTt.rs.
