(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module PartOfExprStmtRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/part_of_expr_stmt_ref.rs', lines 5:0-7:1 *)
Definition fun_name : result i32 :=
  Ok 1%i32.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/part_of_expr_stmt_ref.rs', lines 1:0-3:1 *)
Definition foo : result unit :=
  i <- fun_name; _ <- i32_add i 1%i32; Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/part_of_expr_stmt_ref.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End PartOfExprStmtRef.rs.
