(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module PreserveGenericsFromBody.rs.

(** Trait declaration: [core::default::Default]
    Source: '/rustc/library/core/src/default.rs', lines 107:0-107:24
    Name pattern: core::default::Default *)
Record core_default_Default_t (Self : Type) := mkcore_default_Default_t {
  core_default_Default_t_default : result Self;
}.

Arguments mkcore_default_Default_t { _ }.
Arguments core_default_Default_t_default { _ } _.

(** [rem_cli::func]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/preserve_generics_from_body.rs', lines 1:0-3:1 *)
Definition func
  {T : Type} (coredefaultDefaultInst : core_default_Default_t T) : result T :=
  coredefaultDefaultInst.(core_default_Default_t_default)
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/preserve_generics_from_body.rs', lines 5:0-7:1 *)
Definition main : result unit :=
  Ok tt.

End PreserveGenericsFromBody.rs.
