(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ReferenceMutableParamWithFurtherUsages.rs.

(** [rem_cli::Foo]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_with_further_usages.rs', lines 1:0-3:1 *)
Record Foo_t := mkFoo_t { foo_field : u32; }.

(** [rem_cli::testfn]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_with_further_usages.rs', lines 5:0-9:1 *)
Definition testfn (arg : Foo_t) : result Foo_t :=
  Ok {| foo_field := 16%u32 |}.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_with_further_usages.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End ReferenceMutableParamWithFurtherUsages.rs.
