(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ReferenceMutableParamWithoutFurtherUsagesRef.rs.

(** [rem_cli::Foo]
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_without_further_usages_ref.rs', lines 1:0-3:1 *)
Record Foo_t := mkFoo_t { foo_field : u32; }.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_without_further_usages_ref.rs', lines 9:0-11:1 *)
Definition fun_name (arg : Foo_t) : result Foo_t :=
  Ok {| foo_field := 8%u32 |}
.

(** [rem_cli::testfn]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_without_further_usages_ref.rs', lines 5:0-7:1 *)
Definition testfn (arg : Foo_t) : result Foo_t :=
  fun_name arg.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/reference_mutable_param_without_further_usages_ref.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End ReferenceMutableParamWithoutFurtherUsagesRef.rs.
