(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ReturnFromNestedFnRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn_ref.rs', lines 9:0-16:1 *)
Definition fun_name : result i32 :=
  i32_add 1%i32 1%i32.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn_ref.rs', lines 2:4-6:5 *)
Fixpoint foo_loop : result unit :=
  m <- fun_name; _ <- i32_add 1%i32 m; foo_loop
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn_ref.rs', lines 1:0-7:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn_ref.rs', lines 18:0-20:1 *)
Definition main : result unit :=
  Ok tt.

End ReturnFromNestedFnRef.rs.
