(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ReturnToParent.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_to_parent.rs', lines 1:0-7:1 *)
Definition foo : result i64 :=
  _ <- i32_add 1%i32 1%i32; Ok 1%i64.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_to_parent.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End ReturnToParent.rs.
