(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ReturnFromNestedFn.rs.

(** [rem_cli::foo]: loop 0:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn.rs', lines 2:4-10:5 *)
Fixpoint foo_loop : result unit :=
  m <- i32_add 1%i32 1%i32; _ <- i32_add 1%i32 m; foo_loop
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn.rs', lines 1:0-11:1 *)
Definition foo : result unit :=
  foo_loop.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/return_from_nested_fn.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End ReturnFromNestedFn.rs.
