(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ShouldIncrementSuffixUntilItFindsSpace.rs.

(** [rem_cli::fun_name1]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/should_increment_suffix_until_it_finds_space.rs', lines 1:0-3:1 *)
Definition fun_name1 : result unit :=
  Ok tt.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/should_increment_suffix_until_it_finds_space.rs', lines 5:0-7:1 *)
Definition fun_name : result unit :=
  Ok tt.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/should_increment_suffix_until_it_finds_space.rs', lines 9:0-11:1 *)
Definition main : result unit :=
  Ok tt.

End ShouldIncrementSuffixUntilItFindsSpace.rs.
