(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module TailExprNoExtraControlFlowRef.rs.

(** [core::result::Result]
    Source: '/rustc/library/core/src/result.rs', lines 527:0-527:21
    Name pattern: core::result::Result *)
Inductive core_result_Result_t (T : Type) (E : Type) :=
| Core_result_Result_Ok : T -> core_result_Result_t T E
| Core_result_Result_Err : E -> core_result_Result_t T E
.

Arguments Core_result_Result_Ok { _ } { _ }.
Arguments Core_result_Result_Err { _ } { _ }.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/tail_expr_no_extra_control_flow_ref.rs', lines 5:0-10:1 *)
Definition fun_name : result (core_result_Result_t unit unit) :=
  Ok (Core_result_Result_Err tt)
.

(** [rem_cli::fallible]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/tail_expr_no_extra_control_flow_ref.rs', lines 1:0-3:1 *)
Definition fallible : result (core_result_Result_t unit unit) :=
  fun_name.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/tail_expr_no_extra_control_flow_ref.rs', lines 12:0-14:1 *)
Definition main : result unit :=
  Ok tt.

End TailExprNoExtraControlFlowRef.rs.
