(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module TwoArgumentsFormExprRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_arguments_form_expr_ref.rs', lines 7:0-9:1 *)
Definition fun_name (n : u32) (m : u32) : result u32 :=
  i <- u32_mul n m; u32_add n i
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_arguments_form_expr_ref.rs', lines 1:0-5:1 *)
Definition foo : result u32 :=
  fun_name 2%u32 3%u32.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_arguments_form_expr_ref.rs', lines 11:0-13:1 *)
Definition main : result unit :=
  Ok tt.

End TwoArgumentsFormExprRef.rs.
