(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module TwoVariablesDefinedInsideAndUsedAfterNoRetRef.rs.

(** [rem_cli::fun_name]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_variables_defined_inside_and_used_after_no_ret_ref.rs', lines 7:0-11:1 *)
Definition fun_name (n : i32) : result (i32 * i32) :=
  k <- i32_mul n n; m <- i32_add k 2%i32; Ok (k, m)
.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_variables_defined_inside_and_used_after_no_ret_ref.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  p <- fun_name 1%i32; let (k, m) := p in _ <- i32_add k m; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_variables_defined_inside_and_used_after_no_ret_ref.rs', lines 13:0-15:1 *)
Definition main : result unit :=
  Ok tt.

End TwoVariablesDefinedInsideAndUsedAfterNoRetRef.rs.
