(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module TwoVariablesDefinedInsideAndUsedAfterNoRet.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_variables_defined_inside_and_used_after_no_ret.rs', lines 1:0-6:1 *)
Definition foo : result unit :=
  k <- i32_mul 1%i32 1%i32; m <- i32_add k 2%i32; _ <- i32_add k m; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/two_variables_defined_inside_and_used_after_no_ret.rs', lines 8:0-10:1 *)
Definition main : result unit :=
  Ok tt.

End TwoVariablesDefinedInsideAndUsedAfterNoRet.rs.
