(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [rem_cli] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module VariableDefinedInsideAndUsedAfterNoRet.rs.

(** [rem_cli::foo]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/variable_defined_inside_and_used_after_no_ret.rs', lines 1:0-5:1 *)
Definition foo : result unit :=
  k <- i32_mul 1%i32 1%i32; _ <- i32_add k 1%i32; Ok tt
.

(** [rem_cli::main]:
    Source: '/home/matt/rem-matt/rem-cli/tools/charon_aeneas_test/rust/variable_defined_inside_and_used_after_no_ret.rs', lines 7:0-9:1 *)
Definition main : result unit :=
  Ok tt.

End VariableDefinedInsideAndUsedAfterNoRet.rs.
