[package]
name = "extract_partial_block_single_line"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]

[lints]
workspace = true
